# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Shannon Ellis 
tagline:          'Postdoctoral Fellow'
description:      'You can also find me on  <a href="http://twitter.com/Shannon_E_Ellis">twitter</a> and <a href="https://github.com/ShanEllis">GitHub</a>.'
url:              https://shanellis.github.io/
baseurl:

author:
  name:           'Shannon Ellis'
  url:            https://twitter.com/Shannon_E_Ellis

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ShanEllis/ShanEllis.github.io
